language: go
go:
    - 1.x
env:
    - GO111MODULE=on
os:
  - linux
services:
  - postgresql

script:
    - make test
    - make integration-postgres
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - make image-build
    - make image-push
