language: go
go:
    - 1.x
env:
    - GO111MODULE=on
os:
  - linux
services:
  - postgresql

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
    - make test || travis_terminate 1;
    - make integration-postgres || travis_terminate 1;
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || travis_terminate 1;
    - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ] ; then
        make image-build || travis_terminate 1;
      fi
    - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ] ; then
        make image-push || travis_terminate 1;
      fi
