language: go
go:
    - 1.x
env:
    - GO111MODULE=on
os:
  - linux
services:
  - postgresql

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
    - make test
    - make integration-postgres
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - make image-build
    - make image-push
